CREATE TABLE IF NOT EXISTS job_applications (
  id              VARCHAR(36) PRIMARY KEY DEFAULT UUID(),
  user_id         VARCHAR(36) NOT NULL,
  job_title       TEXT NOT NULL,
  job_url         TEXT,
  job_description TEXT,
  salary_min      DECIMAL(10,2),
  salary_max      DECIMAL(10,2),
  salary_currency VARCHAR(3) DEFAULT 'IDR',
  `location`      VARCHAR(255),
  employment_type ENUM('internship', 'full-time', 'volunteer', 'part-time', 'contract') DEFAULT 'full-time',
  work_type       ENUM('remote', 'hybrid', 'onsite') DEFAULT 'onsite',
  `status`        ENUM('saved', 'applied', 'interview', 'technical_test', 'offer', 'rejected', 'withdraw') DEFAULT 'saved',
  priority        ENUM('low', 'medium', 'high') DEFAULT 'medium',
  applied_date    DATE,
  deadline        DATE,
  notes           TEXT,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_active       BOOL DEFAULT TRUE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_status (user_id, status),
  INDEX idx_user_created (user_id, created_at)
) ENGINE=INNODB;