CREATE TABLE IF NOT EXISTS job_applications (
  id              VARCHAR(36) NOT NULL,
  user_id         VARCHAR(36) NOT NULL,
  position        VARCHAR(100) NOT NULL,
  company         VARCHAR(50) NOT NULL,
  platform        VARCHAR(50) NOT NULL,
  salary          DECIMAL(10,2),
  salary_currency VARCHAR(3) DEFAULT 'IDR',
  `location`      VARCHAR(255),
  employment_type ENUM('internship', 'full-time', 'volunteer', 'part-time', 'contract') DEFAULT 'full-time',
  work_type       ENUM('remote', 'hybrid', 'onsite') DEFAULT 'onsite',
  `status`        ENUM('pending', 'interview', 'offer', 'rejected', 'withdraw') DEFAULT 'pending',
  priority        ENUM('low', 'medium', 'high') DEFAULT 'medium',
  applied_date    DATE,
  notes           TEXT,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  is_active       BOOL DEFAULT TRUE,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_status (user_id, status),
  INDEX idx_user_created (user_id, created_at),
  INDEX idx_user_position (user_id, position)
) ENGINE=INNODB;